version: '3.8'
name: 'mrge-redis'
services:
    redis:
        image: redis:latest
        container_name: redis_latest
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

volumes:
    redis_data:
